# Generated by Django 6.0.5 on 2026-05-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_cashdrawer_cashdrawertransaction_mpesatransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentnotification',
            name='action_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='channel',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('system', 'System'), ('drawer', 'Cash Drawer'), ('inventory', 'Inventory'), ('reports', 'Reports'), ('sales', 'Sales')], default='system', max_length=20),
        ),
    ]
