# Generated by Django 6.0.5 on 2026-05-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0006_notificationchannel_notificationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'M-Pesa transaction',
                'verbose_name_plural': 'M-Pesa transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.mpesatransaction',),
        ),
    ]
