# Generated by Django 6.0.5 on 2026-05-25 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('report_type', models.CharField(choices=[('summary', 'Summary'), ('sales', 'Sales'), ('inventory', 'Inventory'), ('payments', 'Payments'), ('profit', 'Profit')], max_length=30)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('summary', 'Summary'), ('sales', 'Sales'), ('inventory', 'Inventory'), ('payments', 'Payments'), ('profit', 'Profit')], max_length=30)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_url', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('requested_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('saved_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='api.savedreport')),
            ],
        ),
    ]
