# Generated by Django 6.0.5 on 2026-05-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_approvalrequest_branch_terminal_offlinesynclog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'verbose_name': 'Approval request', 'verbose_name_plural': 'Approval requests'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='offlinesynclog',
            options={'verbose_name': 'Offline sync log', 'verbose_name_plural': 'Offline sync logs'},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={'verbose_name': 'Terminal', 'verbose_name_plural': 'Terminals'},
        ),
    ]
