# Generated by Django 6.0.5 on 2026-05-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
