# Generated by Django 6.0.5 on 2026-05-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('storekeeper', 'Store Keeper'), ('salesperson', 'Sales Person')], max_length=20),
        ),
    ]
