# Generated by Django 6.0.5 on 2026-05-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('storekeeper', 'StoreKeeper'), ('cashier', 'Cashier')], default='cashier', max_length=20),
        ),
    ]
