# Generated by Django 6.0.5 on 2026-05-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('supervisor', 'Supervisor'), ('administrator', 'Administrator')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('storekeeper', 'StoreKeeper'), ('cashier', 'Cashier'), ('customer', 'Customer'), ('manager', 'Manager')], default='cashier', max_length=20),
        ),
    ]
