# Generated by Django 6.0.5 on 2026-05-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_access_tier_customuser_two_factor_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
