# Generated by Django 6.0.5 on 2026-05-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_productunit_taxcode_product_wholesale_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.batch',),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
            ],
            options={
                'verbose_name': 'Inventory movement',
                'verbose_name_plural': 'Inventory movements',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.inventorymovement',),
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
            ],
            options={
                'verbose_name': 'Product unit',
                'verbose_name_plural': 'Product units',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.productunit',),
        ),
        migrations.CreateModel(
            name='ProductUnitConversion',
            fields=[
            ],
            options={
                'verbose_name': 'Product unit conversion',
                'verbose_name_plural': 'Product unit conversions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.productunitconversion',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.supplier',),
        ),
    ]
