# Generated by Django 6.0.5 on 2026-05-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_approvalrequest_branch_terminal_offlinesynclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
            ],
            options={
                'verbose_name': 'Report export',
                'verbose_name_plural': 'Report exports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.reportexport',),
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
            ],
            options={
                'verbose_name': 'Saved report',
                'verbose_name_plural': 'Saved reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.savedreport',),
        ),
    ]
