# Generated by Django 6.0.5 on 2026-05-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
