# Generated by Django 6.0.5 on 2026-05-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0004_sale_mpesa_phone_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
