# Generated by Django 6.0.5 on 2026-05-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash_on_delivery', 'Cash on Delivery'), ('bank', 'Bank Transfer'), ('mixed', 'Multiple Methods')], default='mpesa', max_length=30),
        ),
    ]
