# Generated by Django 6.0.5 on 2026-05-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0006_notificationchannel_notificationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.paymentnotification',),
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
            ],
            options={
                'verbose_name': 'Notification channel',
                'verbose_name_plural': 'Notification channels',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.notificationchannel',),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
            ],
            options={
                'verbose_name': 'Notification log',
                'verbose_name_plural': 'Notification logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.notificationlog',),
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
            ],
            options={
                'verbose_name': 'Notification rule',
                'verbose_name_plural': 'Notification rules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.notificationrule',),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
            ],
            options={
                'verbose_name': 'Notification template',
                'verbose_name_plural': 'Notification templates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.notificationtemplate',),
        ),
    ]
