from django.urls import path

from .views import (
    approval_requests,
    branches,
    dashboard_charts,
    dashboard_statistics,
    decide_approval,
    automatic_excel_status,
    download_automatic_excel,
    excel_export,
    excel_import_products,
    excel_template,
    inventory_report,
    offline_sync_logs,
    payments_report,
    react_payment_config,
    rebuild_automatic_excel,
    reports_summary,
    reports_daily_summary,
    reports_top_products,
    reports_transaction_history,
    sales_report,
    terminal_heartbeat,
    terminals,
)


urlpatterns = [
    path('reports/summary/', reports_summary, name='reports_summary'),
    path('reports/sales/', sales_report, name='sales_report'),
    path('reports/inventory/', inventory_report, name='inventory_report'),
    path('reports/payments/', payments_report, name='payments_report'),
    path('dashboard/charts/', dashboard_charts, name='dashboard_charts'),
    path('dashboard/statistics/', dashboard_statistics, name='dashboard_statistics'),
    path('reports/daily-summary/', reports_daily_summary, name='reports_daily_summary'),
    path('reports/transaction-history/', reports_transaction_history, name='reports_transaction_history'),
    path('reports/top-products/', reports_top_products, name='reports_top_products'),
    path('react/payment-config/', react_payment_config, name='react_payment_config'),
    path('branches/', branches, name='branches'),
    path('terminals/', terminals, name='terminals'),
    path('terminals/heartbeat/', terminal_heartbeat, name='terminal_heartbeat'),
    path('approvals/', approval_requests, name='approval_requests'),
    path('approvals/<int:approval_id>/decide/', decide_approval, name='decide_approval'),
    path('offline-sync/', offline_sync_logs, name='offline_sync_logs'),
    path('excel/template/products/', excel_template, name='excel_template_products'),
    path('excel/export/<str:export_type>/', excel_export, name='excel_export'),
    path('excel/import/products/', excel_import_products, name='excel_import_products'),
    path('excel/automatic/', automatic_excel_status, name='automatic_excel_status'),
    path('excel/automatic/rebuild/', rebuild_automatic_excel, name='rebuild_automatic_excel'),
    path('excel/automatic/<str:name>/download/', download_automatic_excel, name='download_automatic_excel'),
]
