# Generated by Django 6.0.5 on 2026-05-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_data',
            field=models.TextField(blank=True),
        ),
    ]
