# Generated by Django 6.0.5 on 2026-05-25 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_supplier_productimage_product_supplier_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_base_unit', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_type', models.CharField(choices=[('sales', 'Sales Tax'), ('purchase', 'Purchase Tax'), ('both', 'Sales and Purchase Tax')], default='sales', max_length=20)),
                ('is_exempt', models.BooleanField(default=False)),
                ('kra_pin', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_products', to='products.productunit'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.taxcode'),
        ),
        migrations.CreateModel(
            name='ProductUnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_quantity', models.PositiveIntegerField(default=1)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='products.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_conversions', to='products.productunit')),
            ],
            options={
                'unique_together': {('product', 'unit')},
            },
        ),
    ]
