# Generated by Django 6.0.5 on 2026-05-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productunit_taxcode_product_wholesale_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'verbose_name': 'Inventory movement', 'verbose_name_plural': 'Inventory movements'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
        migrations.AlterModelOptions(
            name='productunitconversion',
            options={'verbose_name': 'Product unit conversion', 'verbose_name_plural': 'Product unit conversions'},
        ),
        migrations.AlterModelOptions(
            name='taxcode',
            options={'verbose_name': 'Tax code', 'verbose_name_plural': 'Tax codes'},
        ),
    ]
